version: '2'
services:
  app:
    environment:
      - CI=1
    build: .
    command: bash
    volumes:
      - './:/pbmenv'
      - bundle_path:/bundle
    environment:
      - BUNDLE_PATH=/bundle
volumes:
  bundle_path:
