name: Publish to RubyGems

on:
  [workflow_dispatch]

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: Set up Ruby 2.6
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.6
        bundler-cache: true
    - name: Publish to RubyGems
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"

        mkdir -p $HOME/.gem
        touch $HOME/.gem/credentials
        chmod 0600 $HOME/.gem/credentials
        printf -- "---\n:rubygems_api_key: ${RUBYGEMS_API_TOKEN}\n" > $HOME/.gem/credentials
        bundle exec rake release
      env:
        RUBYGEMS_API_TOKEN: "${{secrets.RUBYGEMS_API_TOKEN}}"
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
